package co.edu.icesi.cyk.service.impl;

import co.edu.icesi.cyk.dto.CykDTO;
import co.edu.icesi.cyk.model.Input;
import co.edu.icesi.cyk.model.Terminal;
import co.edu.icesi.cyk.service.CykService;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class CykServiceImpl implements CykService {

    /**
     * It receives the string w and the grammar, calls the method getInitialMatrix() that generates the initial matrix (Xi1),
     * the method fillMatrix() that fills the upper diagonal of the matrix and the constructor method of the response.
     * @param input string w and the context-independent grammar
     * @return CykDTO data transfer object with the response, if the string is generated by the context-independent grammar
     */

    @Override
    public CykDTO grammarDetector(Input input) {
        String[][] x = getInitialMatrix(input);
        fillMatrix(x, input);
        return buildResponse(x, input);
    }

    /**
     * It receives the input and generates the initial matrix (Xn1) with
     * the variables that produce each of the terminals of the string w
     * @param input string w and the context-independent grammar
     * @return the initial matrix (Xn1)
     */

    private String[][] getInitialMatrix(Input input) {
        int n = input.getW().length();
        String[][] x = new String[n][n];
        int i = 0;
        for (String c : input.getW().split("")) {
            List<String> listVal = input.getFnc().stream().filter(t -> t.getStates().stream().anyMatch(s -> s.equals(c))).map(Terminal::getRoot).collect(Collectors.toList());
            x[i++][0] = String.join(",", listVal);
        }
        return x;
    }

    /**
     * It receives the input and fills the matrix with the upper diagonal
     * @param input string w, the context-independent grammar and the initial matrix
     */

    private void fillMatrix(String[][] x, Input input) {
        int n = input.getW().length();
        for (int j = 1; j < n; j++) {
            for (int i = 0; i < (n - j); i++) {
                List<String> tempGroups = new ArrayList<>();
                for (int k = 0; k <= (j - 1); k++) {
                    String[] b = x[i][k].split(",");
                    String[] c = x[i + (k + 1)][j - (k + 1)].split(",");
                    for (String vb : b) {
                        for (String vc : c) {
                            if (!vb.equals("") && !vc.equals("") && !tempGroups.contains(vb + vc))
                                tempGroups.add(vb + vc);
                        }
                    }
                }
                List<String> temp = new ArrayList<>();
                for (String c : tempGroups) {
                    List<String> listVal = input.getFnc().stream().filter(t -> t.getStates().stream().anyMatch(s -> s.equals(c))).map(Terminal::getRoot).collect(Collectors.toList());
                    for (String s : listVal) {
                        if (!temp.contains(s))
                            temp.add(s);
                    }
                }
                x[i][j] = String.join(",", temp);
            }
        }
    }

    /**
     * It receives the input and checks whether the initial state "S" of the grammar is part of the set of variables at position X1n.
     * @param input string w, the context-independent grammar and the matrix
     * @return CykDTO data transfer object with the response, if the string is generated by the context-independent grammar
     */

    private CykDTO buildResponse(String[][] x, Input input) {
        boolean response = Arrays.stream(x[0][input.getW().length() - 1].split(",")).anyMatch(e -> e.equals(input.getFnc().get(0).getRoot()));
        return CykDTO.builder().response(response).build();
    }
}
